name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your default branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Adjust this to the Ruby version your project requires

    - name: Install dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install

    - name: Create .env file
      run: |
        echo "REACT_APP_APP_ENV=${{ secrets.REACT_APP_APP_ENV }}" >> .env
        echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
        echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
        echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
        echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
        echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
        echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> .env
        echo "REACT_DATABASE_URL=${{ secrets.REACT_DATABASE_URL }}" >> .env
        echo "REACT_MEASUREMENT_ID=${{ secrets.REACT_MEASUREMENT_ID }}" >> .env

    - name: Build the Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
